apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-dev
namePrefix: dev-

resources:
  - ../../base

patches:
  - path: replicas.yaml
    target:
      kind: Deployment
      name: web

configMapGenerator:
  - name: web-config
    behavior: merge
    literals:
      - APP_ENV=dev
      - APP_DEBUG=true

images:
  - name: nginx
    newTag: 1.27-alpine
